export const LOAD_REPOS = 'CEDU/App/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'CEDU/App/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'CEDU/App/LOAD_REPOS_ERROR';

export const LOAD_CURRENT_USER = 'CEDU/App/LOAD_CURRENT_USER';
export const LOAD_CURRENT_USER_SUCCESS = 'CEDU/App/LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_ERROR = 'CEDU/App/LOAD_CURRENT_USER_ERROR';

export const LOAD_CURRENT_USER_CONTAINER =
  'CEDU/App/LOAD_CURRENT_USER_CONTAINER';
export const LOAD_CURRENT_USER_CONTAINER_SUCCESS =
  'CEDU/App/LOAD_CURRENT_USER_CONTAINER_SUCCESS';
export const LOAD_CURRENT_USER_CONTAINER_ERROR =
  'CEDU/App/LOAD_CURRENT_USER_CONTAINER_ERROR';

export const UPDATE_CURRENT_USER_CONTAINER =
  'CEDU/App/UPDATE_CURRENT_USER_CONTAINER';
export const UPDATE_CURRENT_USER_CONTAINER_SUCCESS =
  'CEDU/App/UPDATE_CURRENT_USER_CONTAINER_SUCCESS';
export const UPDATE_CURRENT_USER_CONTAINER_ERROR =
  'CEDU/App/UPDATE_CURRENT_USER_CONTAINER_ERROR';

export const UPDATE_TOGGLE_MENU = 'CEDU/App/UPDATE_TOGGLE_MENU';

export const UPDATE_TOGGLE_MENU_ON_MOBILE =
  'CEDU/App/UPDATE_TOGGLE_MENU_ON_MOBILE';

export const UPDATE_MODAL = 'CEDU/App/UPDATE_MODAL';

export const LOGOUT = 'CEDU/App/LOGOUT';
export const LOGOUT_SUCCESS = 'CEDU/App/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'CEDU/App/LOGOUT_ERROR';
